### ISSUE TITLE
decode error?

### ISSUE THREAD

**Issue by xxwlyl** [HNYuuu/SeeWasm#92]
**Describe the bug**
When I try to wasmtime the module, it reports the error 'ttributeError: 'int' object has no attribute 'from_raw''

**To Reproduce**
compile the C code and rerun it with SeeWasm

**Additional context**
the source code is as follows.

#include <stdio.h>

int foo(char a){
    if(a > 10){
        return 0;
    }
    else return 1;
}

int main(int argc, char* argv[]){
    return foo(argv[1][0]);
}

**Comment by HNYuuu** [comment]
Currently, for C programs, we only support Wasm binaries compiled from [wasi-sdk-14](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-14).

Because Wasm is still under develop and maintain, some new syntax or characteristics may break the integrity of the library that decodes Wasm binaries.

Maybe we will support new features in the future.

**Comment by harveyghq** [comment]
Fixed in dca0b51fad7eba439da4b4b2b2792d39bf2a9c72

The compiler toolchain has been updated to [wasi-sdk-22](https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-22).
